core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pdvWeb.urls", namespace='pdvWeb')),
    path('usuario/', include("usuario.urls", namespace='usuario')),
    
    #serve para carregar imagens em modo DEBUG= False
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

#? Arquivos estaticos
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pdvWeb/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *

app_name = 'pdvWeb'

urlpatterns = [
    path('', home, name='home'),
    path('produtos/', produtos, name='produtos'),
    path('cadastrar_produto/', cadastrar_produto, name='cadastrar_produto'),
    path('atualizar_produto/<int:id>', atualizar_produto, name='atualizar_produto'),
    path('deletar_produto/<int:id>', deletar_produto, name='deletar_produto'),
    path('deletar_item_venda/<int:id>', deletar_item_venda, name='deletar_item_venda'),
    path('nova_venda/', nova_venda, name='nova_venda'),
    path('venda/<int:venda_id>/', adicionar_produto, name='adicionar_produto'),
    path('todos_produtos/', todos_produtos, name='todos_produtos'),
    path('buscar_produto/', buscar_produto, name='buscar_produto'),
    path('finalizar_venda/<int:id>', finalizar_venda, name='finalizar_venda'),
    path('retornar_venda/<int:id>', retornar_venda, name='retornar_venda'),
    path('cancelar_venda/<int:id>', cancelar_venda, name='cancelar_venda'),
    path('personalizar/', personalizar, name='personalizar')
    
]

usuario/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *

app_name = 'usuario'

urlpatterns = [
    path('cadastro/', cadastro, name='cadastro'),
    path('login/', login, name='login'),
    path('gerencia/', gerencia, name='gerencia'),
    path('funcionarios/', funcionarios, name='funcionarios'),
    path('cadastrar_funcionario/', cadastrar_funcionario, name='cadastrar_funcionario'),
    path('atualizar_funcionario/<int:id>', atualizar_funcionario, name='atualizar_funcionario'),
    path('deletar_funcionario/<int:id>', deletar_funcionario, name='deletar_funcionario'),
    path('validar_login/', validar_login, name='validar_login' ),
    path('sair/', sair, name='sair'),
    path('vendas/', vendas, name='vendas')
    
    
]

pdvWeb/models.py
from django.db import models
from usuario.models import Funcionario
from datetime import datetime
from django.utils import timezone
import pytz

fuso = pytz.timezone('America/Sao_Paulo')

class CustomStore(models.Model):
    nome = models.CharField(max_length=100, null=True, blank=True)
    logoImage = models.ImageField(upload_to='images/', blank=True, null=True)
    
    def __str__(self) -> str:
       return self.nome

class Produto(models.Model):
  codigo = models.IntegerField(null=False, blank=False)
  descricao = models.CharField(max_length=50, null=False, blank=False)
  valor = models.FloatField(null=False, blank=False)
  quantidade = models.IntegerField(null=False, blank=False)
  
  def __str__(self) -> str:
    return f'Produto: {self.codigo} - {self.descricao}'
  

class Venda(models.Model):
    produtos = models.ManyToManyField(Produto, through='ItemVenda')
    total = models.FloatField(null=False, blank=False)
    data = models.CharField(max_length=255)
    cpf_cliente = models.CharField(max_length=12 ,blank=True, null=True)
    finalizada = models.BooleanField(default=False)
    
    def __str__(self) -> str:
       return f'venda 00{self.id}'
    
    
class ItemVenda(models.Model):
    venda = models.ForeignKey(Venda, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.IntegerField(null=False, blank=False)
    subtotal = models.FloatField(null=False, blank=False)
    
    def __str__(self) -> str:
       return f'Produto {self.produto}'
  
  
class NotaFiscal(models.Model):
  funcionario = models.ForeignKey(Funcionario, on_delete=models.DO_NOTHING, null=False, blank=False)
  venda = models.ForeignKey(Venda, on_delete=models.DO_NOTHING, null=False, blank=False)
  total = models.FloatField(null=False, blank=False)
  
  def __str__(self) -> str:
       return f'Venda 00{self.id} - Funcionario {self.funcionario.nome}'

pdvWeb/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from usuario.models import *
from django.http import JsonResponse
from django.contrib.messages import constants
from django.contrib import messages
from django.utils import timezone
from .utils import *

#---------------------------------------------------------------------------------------------------
# todo                                      Renderização de paginas
#---------------------------------------------------------------------------------------------------
def home(request):
    try:
      venda_aberta = Venda.objects.filter(finalizada=False)
      usuario = request.session.get('usuario')
      request_usuario = Funcionario.objects.get(id = usuario ) 
      return render(request, 'home_pdv.html', {'venda_aberta':venda_aberta,'usuario':request_usuario})
    except:
      return render(request, 'login.html')


def produtos(request):
    produtos = Produto.objects.all()
    usuario = request.session.get('usuario')
    request_usuario = Funcionario.objects.get(id = usuario )
    
    return render(request, 'lista_produtos.html', {'produtos': produtos,'usuario':request_usuario})


def todos_produtos(request):
    produtos = Produto.objects.all().values('codigo', 'descricao', 'valor', 'quantidade')
    produtos_list = list(produtos)  
    return JsonResponse(produtos_list, safe=False)
  
  
#---------------------------------------------------------------------------------------------------
# todo                                      Funções de admin
#---------------------------------------------------------------------------------------------------
def cadastrar_produto(request):
  if request.session.get('usuario'):  
    v_codigo = int(request.POST.get('codigo'))
    v_descricao = request.POST.get('descricao')
    v_valor = float(request.POST.get('valor'))
    v_quantidade = int(request.POST.get('quantidade'))
    
    produto = Produto.objects.filter(codigo = v_codigo)
    if produto.exists():
      messages.error(request, 'ERROR! Código do produto já existe!')
      return redirect('pdvWeb:produtos')
    
    Produto.objects.create(codigo = v_codigo, descricao = v_descricao, valor = v_valor, quantidade = v_quantidade)
    messages.success(request, 'Produto cadastrado com sucesso!')
    return redirect('pdvWeb:produtos')
  else:
      messages.add_message(request, constants.ERROR, 'Usuario não está logado!')
      return redirect('usuario:login')


def atualizar_produto(request, id):
    produto = Produto.objects.get(id = id)
    v_codigo = int(request.POST.get('codigo'))
    v_descricao = request.POST.get('descricao')
    v_valor = request.POST.get('valor')
    v_valor =  v_valor.replace('R$', '')
    v_valor = v_valor.replace(',', '.')
    v_valor = float(v_valor)
    v_quantidade = int(request.POST.get('quantidade'))
    
    if not validar_produto(request, v_codigo, v_descricao, v_valor, v_quantidade ):
        messages.add_message(request, messages.ERROR, 'DEU MERDA!')
        return redirect('pdvWeb:produtos')
    
    
    produto.descricao = v_descricao
    produto.valor = v_valor
    produto.quantidade = v_quantidade
    produto.save()
    
    messages.add_message(request, messages.SUCCESS, 'Produto atualizado com sucesso!')
    return redirect('pdvWeb:produtos')
  

def deletar_produto(request, id):
  produto = Produto.objects.get(id = id)
  
  produto.delete()
  
  return redirect('pdvWeb:produtos') 


def personalizar(request):
    if request.session.get('usuario'): 
      usuario = request.session.get('usuario')
      request_usuario = Funcionario.objects.get(id = usuario )
      return render(request, 'configuracoes.html',{'usuario':request_usuario})
    else:
      messages.add_message(request, constants.ERROR, 'Usuario não está logado!')
      return redirect('usuario:login')
#---------------------------------------------------------------------------------------------------
# todo                                      Funções de venda
#---------------------------------------------------------------------------------------------------

def format_cpf(value):
    return "%s.%s.%s-%s" % (value[0:3], value[3:6], value[6:9], value[9:11])
  
  
def nova_venda(request):
    print(timezone.now())
    try:
      cpf = request.POST.get('cpf')
      venda = Venda.objects.create(total=0, cpf_cliente=cpf, data = timezone.now().strftime("%d-%m-%Y %H:%M:%S"))# Cria uma nova venda com total 0
    except:
      venda = Venda.objects.create(total=0, data = timezone.now().strftime("%d-%m-%Y %H:%M:%S"))# Cria uma nova venda com total 0
    return redirect('pdvWeb:adicionar_produto', venda_id=venda.id)  # Redireciona para a view 'adicionar_produto' com o id da venda


def retornar_venda(request, id):
    try:
        venda = Venda.objects.get(id=id)  # substitua 'Venda' pela classe do seu modelo de venda
    except Venda.DoesNotExist:
        # Redireciona para a página inicial, por exemplo, se a venda não existe
        return redirect('nome_da_sua_url_home')
        
    context = {'venda': venda}
    return render(request, 'venda_pdv.html', context)


def adicionar_produto(request, venda_id):
    usuario = request.session.get('usuario')
    request_usuario = Funcionario.objects.get(id = usuario ) 
    todos_produtos = Produto.objects.all()
    
    venda_aberta = Venda.objects.filter(finalizada=False)
    
    if request.method == 'POST':
        codigo_produto = request.POST['codigo_produto']
        quantidade = request.POST['quantidade']
        if quantidade.strip() == '' or codigo_produto.strip() == '':
          messages.add_message(request, constants.SUCCESS, 'quantidade não pode ser vazio!')
          return redirect('pdvWeb:adicionar_produto', venda_id)
        
        try:
          quantidade = int(quantidade)
          produto = Produto.objects.get(codigo=codigo_produto)
          
                  
          item_venda = ItemVenda.objects.create(
              venda_id=venda_id,
              produto=produto,
              quantidade=quantidade,
              subtotal=produto.valor * quantidade
          )
          
          venda = Venda.objects.get(id=venda_id)
          venda.total += item_venda.subtotal
          venda.save()
        except:
          messages.add_message(request, constants.SUCCESS, 'Codigo do produto invalido!')
          return redirect('pdvWeb:adicionar_produto', venda_id)
          


    venda = Venda.objects.get(id=venda_id)
    itens_venda = ItemVenda.objects.filter(venda_id=venda_id)
    
    return render(request, 'venda_pdv.html', {'venda_aberta':venda_aberta, 'venda': venda, 'itens_venda': itens_venda, 'usuario':request_usuario, 'todos_produtos':todos_produtos})


def buscar_produto(request):
    codigo = request.GET.get('codigo', None)
    try:
        produto = Produto.objects.get(codigo=codigo)
        data = {'produto': {
            'codigo': produto.codigo,
            'descricao': produto.descricao,
            'valor': produto.valor,
            'quantidade': produto.quantidade
        }}
    except Produto.DoesNotExist:
        data = {'produto': None}
    return JsonResponse(data)


def deletar_item_venda(request, id):
      if request.method == 'POST':
        cpf = request.POST.get('cpf')
        
        usuario = Funcionario.objects.filter(cpf = cpf).filter(cargo = 2)
        
        produto = ItemVenda.objects.get(id = id)
        
        if len(usuario) == 0:
          messages.add_message(request, constants.ERROR, 'Matricula invalida!')
          return redirect('pdvWeb:adicionar_produto', produto.venda.id)
        
        
        produto.delete()
        
        produto.venda.total -= produto.subtotal
        produto.venda.save()
        messages.add_message(request, constants.SUCCESS, 'Item deletado com sucesso!')
        return redirect('pdvWeb:adicionar_produto', produto.venda.id) 


def cancelar_venda(request, id):
  if request.method == 'POST':
        cpf = request.POST.get('cpf')
        
        usuario = Funcionario.objects.filter(cpf = cpf).filter(cargo = 2)
        
        venda = Venda.objects.get(id = id)
        
        if len(usuario) == 0:
          messages.add_message(request, constants.ERROR, 'Matricula invalida!')
          return redirect('pdvWeb:adicionar_produto' , venda.id)
  
  venda = Venda.objects.get(id = id)
  
  venda.delete()
  
  messages.add_message(request, constants.SUCCESS, 'Venda cancelada!')
  return redirect('pdvWeb:home') 


def finalizar_venda(request, id):
    usuario = request.session.get('usuario')
    request_usuario = Funcionario.objects.get(id = usuario ) 
    if request.method == 'POST':
      recebido = request.POST.get('recebido')
      venda = Venda.objects.get(id=id)
      
      nota_fiscal = NotaFiscal(funcionario=request_usuario, venda=venda, total = venda.total)
      nota_fiscal.save()
      
      venda.finalizada = True
      venda.save()
            
      
      # formatar o CPF
      cpf_cliente = format_cpf(venda.cpf_cliente)
      itens = ItemVenda.objects.filter(venda=venda)
      for i in itens:
        i.produto.quantidade -= i.quantidade
        i.produto.save()
        
      troco = float(recebido) - float(venda.total)
      context = {'recebido':recebido,
                 'troco':troco,
                 'itens':itens,
                 'venda':venda,
                 'nota_fiscal':nota_fiscal,
                 'cpf_cliente': cpf_cliente
                 }
      
      return render(request, 'notaFiscal.html', context)
    
    

pdvWeb/templates/lista_produtos.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
   <head>
      <title>PDV Web</title>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      <link rel="stylesheet" href="{% static 'pdv/css/style.css' %}">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
      <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
      <!-- Default theme -->
      <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>
   </head>
   <body>
      <div class="container-fluid">
      <div class="row">
      <div class="col-2 sidebar">
         <h3><a href="{% url 'pdvWeb:home' %}" class="logo"><img src="{% static 'pdv/img/logoVenda.png' %}" alt="DefPdv" style="width:250px; margin-top: -6rem;"></a></h3>
         {% if usuario %}
         <div class="usuario-info">
            <p id="datetime" class="card-text"></p>
            <!-- Novo parágrafo para a data e hora -->
            <p><i class="bi bi-person-circle"></i> {{usuario.nome}}</p>
            <p><i class="bi bi-upc-scan"></i> {{usuario.cpf}}</p>
            <p><i class="bi bi-bag"></i> {{usuario.cargo.nome}}</p>
         </div>
         <div class="action-usuario">
            <a href="{% url 'usuario:sair' %}" class="nav-link">Logout</a>
         </div>
         {% else %}
         <a href="{% url 'usuario:login' %}" class="nav-link">Login</a>
         {% endif %}
      </div>
      <div class="col main">
      <div class="container my-5">
      <h1 class="text-center mb-4 title"><i class="bi bi-basket-fill"></i> Lista de Produtos</h1>
      <div class="table-responsive">
        <div class="product-list " style="max-height:450px; overflow:auto;">
         <table class="table table-striped table-hover">
            <thead>
               <tr>
                  <th>Código</th>
                  <th>Descrição</th>
                  <th>Valor</th>
                  <th>Quantidade</th>
                  <th colspan="2">Ações</th>
               </tr>
            </thead>
            <tbody>
               {% for produto in produtos %}
               <tr>
                  <td>{{produto.codigo}}</td>
                  <td>{{produto.descricao}}</td>
                  <td>R${{produto.valor|floatformat:2}}</td>
                  {% if produto.quantidade <= 100 %}
                  <td><span class="badge bg-danger text-white">{{produto.quantidade}} <i class="bi bi-arrow-bar-down"></i></span></td>
                  {% elif produto.quantidade > 100 and produto.quantidade < 150  %}
                      <td><span class="badge bg-warning text-dark">{{produto.quantidade}} <i class="bi bi-arrows-collapse"></i></span></td>
                  {% else %}
                      <td><span class="badge bg-success text-white">{{produto.quantidade}} <i class="bi bi-arrow-bar-up"></i></span></td>
                  {% endif %}
              
                  
                  <td><a href="javascript:void(0)"  data-toggle="modal" data-target="#atualizarProduto-{{produto.id}}"><i class="bi bi-pencil-square"></i> Atualizar</a></td>
                  <td><a href="{% url 'pdvWeb:deletar_produto' produto.id %}" style="color:red;"><i class="bi bi-trash-fill"></i> Deletar</a></td>
               </tr>
               <!-- Modal de confirmação de cancelamento de venda -->
               <div class="modal fade" id="atualizarProduto-{{produto.id}}" tabindex="-1" role="dialog" aria-labelledby="finalizarVendaModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                     <div class="modal-content">
                        <div class="modal-header">
                           <h5 class="modal-title" id="finalizarVendaModalLabel">Atualizar produto</h5>
                           <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                           <span aria-hidden="true">&times;</span>
                           </button>
                        </div>
                        <div class="modal-body">
                           <form action="{% url 'pdvWeb:atualizar_produto' produto.id %}" method="POST">
                              {% csrf_token %}
                              <div class="form-group">
                                 <label for="codigo">Código:</label>
                                 <input type="number" class="form-control" name="codigo" id="codigo" value="{{produto.codigo}}" placeholder="Digite o código do produto" required>
                              </div>
                              <div class="form-group">
                                 <label for="descricao">Descrição:</label>
                                 <input type="text" class="form-control" name=descricao id="descricao" value="{{produto.descricao}}" placeholder="Digite o nome do produto" required>
                              </div>
                              <div class="form-group">
                                 <label for="valor">Valor (Unidade):</label>
                                 <input type="text" class="form-control" name=valor id="valor" value="R${{produto.valor|floatformat:2}}" step=".01" placeholder="Digite o valor do produto" required>
                              </div>
                              <div class="form-group">
                                 <label for="quantidade">Quantidade:</label>
                                 <input type="number" class="form-control" name=quantidade id="quantidade" value="{{produto.quantidade}}" placeholder="Digite a quantidade do produto" step=".01" required>
                              </div>
                              <button type="submit" class="btn btn-primary">Atualizar</button>
                              <a href="{% url 'pdvWeb:produtos' %}" class="btn btn-primary">Voltar</a>
                           </form>
                        </div>
                     </div>
                  </div>
                  {% endfor %}
            </tbody>
         </table>
         </div>
         </div>
         <div class="text-left mb-3">
            <a href="javascript:void(0)" class="btn btn-cadastrar"  data-toggle="modal" data-target="#cadastrarProduto"><i class="bi bi-clipboard2-plus-fill"></i> Cadastrar Produto</a>
            <a href="{% url 'usuario:gerencia' %}" class="btn btn-cadastrar"><i class="bi bi-arrow-return-left"></i> Voltar</a>
         </div>
         <div class="text-center">
            <h5 class="text-center">Legenda do Estoque</h5>
            <span class="badge bg-danger text-white">Vermelho: Estoque baixo (0 - 100)</span>
            <span class="badge bg-warning text-dark">Amarelo: Alerta (101 - 150)</span>
            <span class="badge bg-success text-white">Verde: Acima de 150</span><br>
            <span class="text-center">Os valores podem ser ajustados para melhor controle!</span>
         </div>
         
      </div>
   </body>
   <!-- Modal de confirmação de cancelamento de venda -->
   <div class="modal fade" id="cadastrarProduto"  role="dialog" aria-labelledby="finalizarVendaModalLabel" aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title" id="finalizarVendaModalLabel"> Novo Produto</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <form action="{% url 'pdvWeb:cadastrar_produto' %}" method="POST">
               {% csrf_token %}
               <div class="form-group">
                  <label for="codigo">Código:</label>
                  <input type="number" class="form-control" name="codigo" id="codigo" placeholder="Digite o código do produto" required>
               </div>
               <div class="form-group">
                  <label for="descricao">Descrição:</label>
                  <input type="text" class="form-control" name=descricao id="descricao" placeholder="Digite o nome do produto" required>
               </div>
               <div class="form-group">
                  <label for="valor">Valor (Unidade):</label>
                  <input type="text" class="form-control" name=valor id="valor" placeholder="Digite o valor do produto" required>
               </div>
               <div class="form-group">
                  <label for="quantidade">Quantidade:</label>
                  <input type="number" class="form-control" name=quantidade id="quantidade" placeholder="Digite a quantidade do produto" step=".01" required>
               </div>
               <button type="submit" class="btn btn-primary">Cadastrar</button>
               <a href="{% url 'pdvWeb:produtos' %}" class="btn btn-primary">Voltar</a>
            </form>
         </div>
      </div>
   </div>


   <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
   <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
   <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
   <script>
      alertify.set('notifier','position', 'top-right');
      {% for message in messages %}
          {% if message.tags == 'success' %}
              alertify.success('{{message}}');
          {% elif message.tags == 'error' %}
              alertify.error('{{message}}');
          {% else %}
              alertify.notify('{{message}}');
          {% endif %}
      {% endfor %}
  </script>
   <script>
      var dt = new Date();
      document.getElementById("datetime").innerHTML = '<i class="bi bi-clock-history"></i> ' + dt.toLocaleString();
      
      setInterval(function() {
          dt = new Date();
          document.getElementById("datetime").innerHTML = '<i class="bi bi-clock-history"></i> ' + dt.toLocaleString();
      }, 1000);
   </script>
   <script src="https://kit.fontawesome.com/a076d05399.js"></script>
   <script>
      $(window).on('unload', function(){
          navigator.sendBeacon("{% url 'usuario:sair' %}", {});
      });
  </script>
</html>

pdvWeb/templates/notaFiscal.html
{% load static %}
<!DOCTYPE html>
<html>
   <head>
      <style>
         body {
         display: flex;
         justify-content: center;
         align-items: center;
         height: 100vh;
         margin: 0;
         padding: 0;
         box-sizing: border-box;
         background-color: #f4f4f4;
         }
         .card {
         display: flex;
         justify-content: center;
         align-items: center;
         width: 70%;
         background-color: #fff;
         border-radius: 20px;
         padding: 20px;
         box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.15);
         }
         .printer-ticket {
         display: table;
         width: 100%;
         max-width: 400px;
         font-family: Tahoma, Geneva, sans-serif;
         font-size: 10px;
         line-height: 1.3em;
         text-align: center;  /* centraliza todo o texto */
         }
         .printer-ticket * {
         line-height: 1.3em;
         }
         .printer-ticket td, .printer-ticket th {
         padding: 10px;
         border-bottom: 1px dashed #bcbcbc;
         text-align: center;  /* adicionado */ 
         font-size: 1.2em; /* define tamanho da fonte para 1.2em */ 
         }
         .printer-ticket th.title {
         font-size: 3em;
         padding: 15px 0;
         }
         .printer-ticket .sup td {
         padding: 10px 0;
         border-top: 1px dashed #bcbcbc;
         }
         .printer-ticket .sup.p--0 td {
         padding-bottom: 0;
         }
         .printer-ticket h1 {
         font-size: 1.8em; /* aumenta de 1.5em para 1.8em */ 
         }
         .printer-ticket small {
         font-size: 1em;  /* adicionado */  
         }
         table {
         margin: 0 auto;  /* adicionado */
         }
      </style>
   </head>
   <body>
      <div class="card" >
      <section class="printer-ticket" id="pdf-content">
         <a href="{% url 'pdvWeb:home' %}" class="logo"><img src="{% static 'pdv/img/DefPdv.png' %}" alt="DefPdv" style="width:250px; margin-top: -4rem; margin-bottom: -5rem;"></a>
         <h1>Mercadinho LA ELE!</h1>
         <small><time datetime="2020-01-01">{{venda.data}}</time></small>
         <h2>Cliente</h2>
         <small>{{cpf_cliente}}</small>
         <h3>Cupom não fiscal</h3>
         <table>
            <thead>
               <tr>
                  <th colspan="2">Descrição</th>
                  <th>Valor Unit.</th>
                  <th>Qtd.</th>
                  <th>Total</th>
               </tr>
            </thead>
            <tbody>
               {% for itens in itens  %}
               <tr>
                  <td colspan="2">{{itens.produto}}</td>
                  <td>R$ {{itens.produto.valor|floatformat:2}}</td>
                  <td>{{itens.quantidade}}</td>
                  <td>R$ {{itens.subtotal|floatformat:2}}</td>
               </tr>
               {% endfor %}
            </tbody>
         </table>
         <p><strong>Totais</strong></p>
         <p>Sub-total: R${{venda.total|floatformat:2}}</p>
         <p>Desconto: 0,00%</p>
         <p>Total: R${{venda.total|floatformat:2}}</p>
         <p><strong>Pagamentos</strong></p>
         <p>Dinheiro: R${{recebido|floatformat:2}}</p>
         <p>Total pago: R${{venda.total|floatformat:2}}</p>
         <p>Troco: R${{troco|floatformat:2}}</p>
         <h3>Venda -  00{{venda.id}}</h3>
         <h3>Caixa - {{nota_fiscal.funcionario.cpf}}</h3>
      </section>
      <button id="download-pdf">Emitir nota</button>
   </body>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.3/html2pdf.bundle.min.js"></script>
   <script>
      // Adiciona um event listener ao botão "Download PDF"
      document.getElementById("download-pdf").addEventListener("click", function() {
          // Obtém o conteúdo HTML da página
          var elementHTML = document.getElementById("pdf-content");
      
          // Cria as opções de configuração para o html2pdf
          var opt = {
              margin: [15, 15, 15, 15],
              filename: 'mercadinho.pdf',
              image: { type: 'jpeg', quality: 0.98 },
              html2canvas: { scale: 2 },
              jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
          };
      
          // Converte o elemento HTML para PDF usando html2pdf
          html2pdf().set(opt).from(elementHTML).save();
      });
   </script>
</html>