core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pdvWeb.urls", namespace='pdvWeb')),
    path('usuario/', include("usuario.urls", namespace='usuario')),
    
    #serve para carregar imagens em modo DEBUG= False
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

#? Arquivos estaticos
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pdvWeb/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *

app_name = 'pdvWeb'

urlpatterns = [
    path('', home, name='home'),
    path('produtos/', produtos, name='produtos'),
    path('cadastrar_produto/', cadastrar_produto, name='cadastrar_produto'),
    path('atualizar_produto/<int:id>', atualizar_produto, name='atualizar_produto'),
    path('deletar_produto/<int:id>', deletar_produto, name='deletar_produto'),
    path('deletar_item_venda/<int:id>', deletar_item_venda, name='deletar_item_venda'),
    path('nova_venda/', nova_venda, name='nova_venda'),
    path('venda/<int:venda_id>/', adicionar_produto, name='adicionar_produto'),
    path('todos_produtos/', todos_produtos, name='todos_produtos'),
    path('buscar_produto/', buscar_produto, name='buscar_produto'),
    path('finalizar_venda/<int:id>', finalizar_venda, name='finalizar_venda'),
    path('retornar_venda/<int:id>', retornar_venda, name='retornar_venda'),
    path('cancelar_venda/<int:id>', cancelar_venda, name='cancelar_venda'),
    path('personalizar/', personalizar, name='personalizar')
    
]

usuario/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *

app_name = 'usuario'

urlpatterns = [
    path('cadastro/', cadastro, name='cadastro'),
    path('login/', login, name='login'),
    path('gerencia/', gerencia, name='gerencia'),
    path('funcionarios/', funcionarios, name='funcionarios'),
    path('cadastrar_funcionario/', cadastrar_funcionario, name='cadastrar_funcionario'),
    path('atualizar_funcionario/<int:id>', atualizar_funcionario, name='atualizar_funcionario'),
    path('deletar_funcionario/<int:id>', deletar_funcionario, name='deletar_funcionario'),
    path('validar_login/', validar_login, name='validar_login' ),
    path('sair/', sair, name='sair'),
    path('vendas/', vendas, name='vendas')
    
    
]

usuario/models.py
from django.db import models

class Cargo(models.Model):
  nome = models.CharField(max_length=30)
  
  def __str__(self) -> str:
    return self.nome


class Funcionario(models.Model):
  cpf = models.CharField(max_length=11, null=False, blank=False)
  nome = models.CharField(max_length=50, null=False, blank=False)
  cargo = models.ForeignKey(Cargo, on_delete=models.CASCADE, null=False, blank=False)
  esta_logado = models.BooleanField(default=False)
  
  def __str__(self) -> str:
    return self.nome

usuario/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from hashlib import sha256, sha1
from django.contrib.messages import constants
from django.contrib import messages
from pdvWeb.models import *
from django.db.models import Sum
import datetime

#---------------------------------------------------------------------------------------------------
# todo                                      Renderização de paginas
#---------------------------------------------------------------------------------------------------

def cadastro(request):
  cargos = Cargo.objects.all()
  
  return render(request, 'cadastro.html', {'cargos': cargos})


def login(request):
  return render(request, 'login.html')


def sair(request):
    usuario_id = request.session.get('usuario')
    if usuario_id is not None:
        funcionario = Funcionario.objects.get(id=usuario_id)
        funcionario.esta_logado = False
        funcionario.save()
  
  
    messages.success(request,  'Você saiu do portal!')
    request.session.flush()
    return redirect('usuario:login')


def gerencia(request):
    usuario = request.session.get('usuario')
    request_usuario = Funcionario.objects.get(id = usuario ) 
    return render(request, 'gerencia.html', {'usuario':request_usuario})


def funcionarios(request):
  if request.session.get('usuario'):  
    funcionarios = Funcionario.objects.all()
    usuario = request.session.get('usuario')
    request_usuario = Funcionario.objects.get(id = usuario )
    cargos = Cargo.objects.all()
    
    return render(request, 'funcionarios.html', {'cargos':cargos,'funcionarios': funcionarios,'usuario':request_usuario})
  else:
      messages.add_message(request, constants.ERROR, 'Usuario não está logado!')
      return redirect('usuario:login')


#---------------------------------------------------------------------------------------------------
# todo                                      Renderização de admin
#---------------------------------------------------------------------------------------------------

def validar_login(request):
    nome = request.POST.get('nome')
    cpf = request.POST.get('cpf')  
    
    try:
        funcionario = Funcionario.objects.get(nome=nome, cpf=cpf)
    except Funcionario.DoesNotExist:
        messages.add_message(request, constants.ERROR, 'Nome ou CPF inválidos!')
        return redirect('usuario:login')

    funcionario.esta_logado = True
    funcionario.save()
    
    if funcionario.cargo.nome == 'Gerente':  
      messages.add_message(request, constants.SUCCESS, 'Gerente logado com sucesso!')
      request.session['usuario'] = funcionario.id
      return redirect('usuario:gerencia')
    else: 
      
      messages.add_message(request, constants.SUCCESS, 'Funcionario logado com sucesso!')
      request.session['usuario'] = funcionario.id
      return redirect('pdvWeb:home')

      
def vendas(request):
    if request.session.get('usuario'):  
      usuario = request.session.get('usuario')
      funcionarios = Funcionario.objects.all()
      request_usuario = Funcionario.objects.get(id = usuario ) 
      total_venda = NotaFiscal.objects.all()
      valor_bruto_vendas = NotaFiscal.objects.aggregate(Sum('total'))['total__sum']
      ticket_medio = valor_bruto_vendas / len(total_venda)
      ranking_funcionarios = (
      NotaFiscal.objects.values('funcionario__nome')  # Agrupa por nome do funcionário
      .annotate(vendas_total=Sum('total'))  # Soma o total de cada grupo
      .order_by('-vendas_total')  # Ordena em ordem decrescente pelo total de vendas
      )    
      
      top_vendedor = ranking_funcionarios.first()
      top_vendedor = top_vendedor['funcionario__nome']
      # Obter a data atual
      data_atual = timezone.now().date()

      # Consulta para obter o total de vendas do dia atual
      vendas_dia = Venda.objects.filter(data__startswith=data_atual.strftime('%d-%m-%Y'), finalizada=True).aggregate(total_vendas=Sum('total'))['total_vendas']
      historico_venda = Venda.objects.filter(data__startswith=data_atual.strftime('%d-%m-%Y'), finalizada=True)

      vendas = []
      for venda in historico_venda:
          notas_fiscais = NotaFiscal.objects.filter(venda=venda)
          for nota_fiscal in notas_fiscais:
              vendas.append({
                  'total': venda.total,
                  'funcionario': nota_fiscal.funcionario.nome,
                  'data_venda': venda.data
              })

      # Pega todos os produtos com quantidade em estoque abaixo de 100
      produtos_estoque_baixo = Produto.objects.filter(quantidade__lt=100)

      # Pega os 5 produtos mais vendidos
      produtos_mais_vendidos = ItemVenda.objects.values('produto__codigo', 'produto__descricao').annotate(total_vendido=Sum('quantidade')).order_by('-total_vendido')[:5]

      numero_funcionarios_logados = Funcionario.objects.filter(esta_logado=True).count()

      # Pega a quantidade vendida do produto mais vendido
      print(produtos_mais_vendidos)
      context ={
        'usuario':request_usuario,
        'total_venda':total_venda,
        'valor_bruto':valor_bruto_vendas,
        'ticket_medio':ticket_medio,
        'ranking':ranking_funcionarios,
        'top_vendedor':top_vendedor,
        'vendas_dia':vendas_dia,
        'historico_venda':vendas,
        'produto_mais_vendido':produtos_mais_vendidos,
        'estoque_baixo':produtos_estoque_baixo,
        'funcionarios':funcionarios,
        'numero_funcionarios_logados':numero_funcionarios_logados
        }
      
      return render(request, 'vendas.html', context)
    else:
      messages.add_message(request, constants.ERROR, 'Usuario não está logado!')
      return redirect('usuario:login')


def cadastrar_funcionario(request):
  if request.session.get('usuario'):  
    v_nome = request.POST.get('nome')
    v_cpf = request.POST.get('cpf')
    v_cargo = request.POST.get('cargo')
    cargo = Cargo.objects.get(id = v_cargo)
    
    funcionario = Funcionario.objects.filter(cpf=v_cpf)
    if funcionario.exists():
      messages.error(request,  'ERROR! CPF já está cadastrado!')
      return redirect('usuario:funcionarios')
    
    Funcionario.objects.create(nome = v_nome, cpf = v_cpf, cargo = cargo)
    
    messages.success(request,  'Funcionario cadastrado com sucesso!')
    return redirect('usuario:funcionarios')
  else:
      messages.add_message(request, constants.ERROR, 'Usuario não está logado!')
      return redirect('usuario:login')
  
  
def atualizar_funcionario(request, id):
  funcionario = Funcionario.objects.get(id = id)
  
  v_nome = request.POST.get('nome')
  v_cpf = request.POST.get('cpf')
  v_cargo = request.POST.get('cargo')
  cargo = Cargo.objects.get(id = v_cargo)
  
  funcionario.nome = v_nome
  funcionario.cpf = v_cpf
  funcionario.cargo = cargo
  
  funcionario.save()
  messages.add_message(request, constants.SUCCESS, 'Funcionario atualizado com sucesso!')
  return redirect('usuario:funcionarios')


def deletar_funcionario(request, id):
  funcionario = Funcionario.objects.get(id = id)
  
  funcionario.delete()
  messages.add_message(request, constants.SUCCESS, 'Funcionario excluido com sucesso!')
  return redirect('usuario:funcionarios')
  

usuario/templates/funcionarios.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
   <head>
      <title>PDV Web</title>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      <link rel="stylesheet" href="{% static 'pdv/css/style.css' %}">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
      <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
      <!-- Default theme -->
      <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>
   </head>
   <body>
      <div class="container-fluid">
      <div class="row">
      <div class="col-2 sidebar">
         <h3><a href="{% url 'pdvWeb:home' %}" class="logo"><img src="{% static 'pdv/img/logoVenda.png' %}" alt="DefPdv" style="width:250px; margin-top: -6rem;"></a></h3>
         {% if usuario %}
         <div class="usuario-info">
            <p id="datetime" class="card-text"></p>
            <!-- Novo parágrafo para a data e hora -->
            <p><i class="bi bi-person-circle"></i> {{usuario.nome}}</p>
            <p><i class="bi bi-upc-scan"></i> {{usuario.cpf}}</p>
            <p><i class="bi bi-bag"></i> {{usuario.cargo.nome}}</p>
         </div>
         <div class="action-usuario">
            <a href="{% url 'usuario:sair' %}" class="nav-link">Logout</a>
         </div>
         {% else %}
         <a href="{% url 'usuario:login' %}" class="nav-link">Login</a>
         {% endif %}
      </div>
      <div class="col main">
        <div class="container my-5">
        <h1 class="text-center mb-4 title"><i class="bi bi-person-lines-fill"></i> Lista de Funcionarios</h1>
        <div class="table-responsive">
          <div class="product-list " style="max-height:500px; overflow:auto;">
           <table class="table table-striped table-hover">
            <thead>
               <tr>
                  <th>Nome</th>
                  <th>Cargo</th>
                  <th>Matricula</th>
                  <th>Atualizar</th>
                  <th>Deletar</th>
               </tr>
            </thead>
            <tbody>
               {% for funcionario in funcionarios %}
               <tr>
                  <td>{{funcionario.nome}}</td>
                  <td>{{funcionario.cargo}}</td>
                  <td>{{funcionario.cpf}}</td>
                  <td><a href="javascript:void(0)" data-toggle="modal" data-target="#updateEmployeeModal-{{funcionario.id}}"><i class="bi bi-pencil-square"></i> Atualizar</a></td>
                  <td><a href="{% url 'usuario:deletar_funcionario' funcionario.id %}" style="color:red;" ><i class="bi bi-trash-fill"></i> Deletar</a></td>
               </tr>
               <!-- Modal de confirmação de cancelamento de venda -->
               <div class="modal fade" id="updateEmployeeModal-{{funcionario.id}}" tabindex="-1" role="dialog" aria-labelledby="finalizarVendaModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                     <div class="modal-content">
                        <div class="modal-header">
                           <h5 class="modal-title" id="finalizarVendaModalLabel">Atualizar funcionario</h5>
                           <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                           <span aria-hidden="true">&times;</span>
                           </button>
                        </div>
                        <div class="modal-body">
                           <form action="{% url 'usuario:atualizar_funcionario' funcionario.id %}" method="POST">
                              {% csrf_token %}
                              <div class="form-group">
                                 <label for="nome">Nome:</label>
                                 <input type="text" class="form-control" name="nome" id="nome" value="{{funcionario.nome}}" required>
                              </div>
                              <div class="form-group">
                                 <label for="cpf">CPF:</label>
                                 <input type="text" class="form-control" name="cpf" id="cpf" value="{{funcionario.cpf}}" maxlength="11" required>
                              </div>
                              <div class="form-group">
                                 <label for="cargo">Cargo:</label>
                                 <select class="form-control" name="cargo" id="cargo" required>
                                    {% for cargo in cargos %}
                                    {% if cargo == funcionario.cargo %}
                                    <option value="{{ cargo.id }}" selected>{{ cargo.nome }}</option>
                                    {% else %}
                                    <option value="{{ cargo.id }}">{{ cargo.nome }}</option>
                                    {% endif %}
                                    {% endfor %}
                                 </select>
                              </div>
                              <div class="modal-footer">
                                 <button type="submit" class="btn btn-primary">Salvar</button>
                              </div>
                           </form>
                        </div>
                     </div>
                  </div>
                  {% endfor %}
         </table>
         </div>
         </div>
         <a href="javascript:void(0)" class="btn btn-cadastrar" data-toggle="modal" data-target="#cadastrarFuncionario"><i class="bi bi-clipboard2-plus-fill"></i> Cadastrar Usuário</a>
         <a href="{% url 'usuario:gerencia' %}" class="btn btn-cadastrar"><i class="bi bi-arrow-return-left"></i> Voltar</a>
         </div>
      </div>
   </body>
   <!-- Modal de confirmação de cancelamento de venda -->
   <div class="modal fade" id="cadastrarFuncionario"  role="dialog" aria-labelledby="finalizarVendaModalLabel" aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title" id="finalizarVendaModalLabel">Novo Funcionario</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <form action="{% url 'usuario:cadastrar_funcionario' %}" method="POST">
               {% csrf_token %}
               <div class="form-group">
                  <label for="nome">Nome:</label>
                  <input type="text" class="form-control" name="nome" id="nome" placeholder="Digite o nome do funcionário" required>
               </div>
               <div class="form-group">
                  <label for="cpf">CPF:</label>
                  <input type="text" class="form-control" name=cpf id="cpf" placeholder="Digite o CPF do funcionário" maxlength="11" required>
               </div>
               <div class="form-group">
                  <label for="cargo">Cargo:</label>
                  <select class="form-control" name="cargo" id="cargo" required>
                     {% for cargo in cargos %}
                     <option value="{{ cargo.id }}">{{ cargo.nome }}</option>
                     {% endfor %}
                  </select>
               </div>
               <button type="submit" class="btn btn-primary">Cadastrar</button>
               <a href="{% url 'usuario:funcionarios' %}" class="btn btn-primary">Voltar</a>
            </form>
         </div>
      </div>
   </div>
   <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
   <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
   <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
   <script>
      alertify.set('notifier','position', 'top-right');
      {% for message in messages %}
          {% if message.tags == 'success' %}
              alertify.success('{{message}}');
          {% elif message.tags == 'error' %}
              alertify.error('{{message}}');
          {% else %}
              alertify.notify('{{message}}');
          {% endif %}
      {% endfor %}
  </script>
   <script>
      var dt = new Date();
      document.getElementById("datetime").innerHTML = '<i class="bi bi-clock-history"></i> ' + dt.toLocaleString();
      
      setInterval(function() {
          dt = new Date();
          document.getElementById("datetime").innerHTML = '<i class="bi bi-clock-history"></i> ' + dt.toLocaleString();
      }, 1000);
   </script>
   <script src="https://kit.fontawesome.com/a076d05399.js"></script>
   <script>
      $(window).on('unload', function(){
          navigator.sendBeacon("{% url 'usuario:sair' %}", {});
      });
  </script>
</html>

usuario/templates/gerencia.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
   <head>
      <title>PDV Web</title>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      <link rel="stylesheet" href="{% static 'pdv/css/style.css' %}">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
      <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
      <!-- Default theme -->
      <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>

   </head>
   <body>
      <div class="container-fluid">
      <div class="row">
      <div class="col-2 sidebar">
         <h3><a href="{% url 'pdvWeb:home' %}" class="logo"><img src="{% static 'pdv/img/logoVenda.png' %}" alt="DefPdv" style="width:250px; margin-top: -6rem;"></a></h3>
         {% if usuario %}
         <div class="usuario-info">
            <p id="datetime" class="card-text"></p>
            <!-- Novo parágrafo para a data e hora -->
            <p><i class="bi bi-person-circle"></i> {{usuario.nome}}</p>
            <p><i class="bi bi-upc-scan"></i> {{usuario.cpf}}</p>
            <p><i class="bi bi-bag"></i> {{usuario.cargo.nome}}</p>
         </div>
         <div class="action-usuario">
            <a href="{% url 'usuario:sair' %}" class="nav-link">Logout</a>
         </div>
         {% else %}
         <a href="{% url 'usuario:login' %}" class="nav-link">Login</a>
         {% endif %}
      </div>
      <div class="col main" style="height: 100%;   background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)),  background-size: cover;">
         <div class="add-product text-center">
            <img src="{% static 'pdv/img/defPDVLogo.png' %}" alt="Some description" style="width:550px;"><br>
            <br><br>
            <h1><strong>ADMININSTRAÇÃO</strong></h1>

            <!-- <a href="{% url 'pdvWeb:nova_venda' %}" class="btn btn-primary mt-4">Iniciar Venda</a> -->
         </div>
         <br><br>
         <div class="row mt-4 d-flex justify-content-center align-items-center">
            <div class="col-md-3">
               <div class="card">
                  <div class="card-body text-center">
                     <a href="{% url 'usuario:funcionarios' %}">
                        <i class="fas fa-user fa-3x"></i>
                        <h5 class="card-title mt-2">Funcionário</h5>
                     </a>
                  </div>
               </div>
            </div>
            <div class="col-md-3">
               <div class="card">
                  <div class="card-body text-center">
                     <a href="{% url 'pdvWeb:produtos' %}">
                        <i class="fas fa-shopping-cart fa-3x"></i>
                        <h5 class="card-title mt-2">Produto</h5>
                     </a>
                  </div>
               </div>
            </div>
            <div class="col-md-3">
               <div class="card">
                  <div class="card-body text-center">
                     <a href="{% url 'usuario:vendas' %}">
                        <i class="fas fa-chart-line fa-3x"></i>
                        <h5 class="card-title mt-2">Vendas</h5>
                     </a>
                  </div>
               </div>
            </div>
            <div class="col-md-3">
               <div class="card">
                  <div class="card-body text-center">
                     <a href="{% url 'pdvWeb:personalizar' %}">
                        <i class="fa fa-cog fa-3x"></i>
                        <h5 class="card-title mt-2">Configurações da loja</h5>
                     </a>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </body>
   <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
   <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
   <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
   <script>
      alertify.set('notifier','position', 'top-right');
      {% for message in messages %}
          {% if message.tags == 'success' %}
              alertify.success('{{message}}');
          {% elif message.tags == 'error' %}
              alertify.error('{{message}}');
          {% else %}
              alertify.notify('{{message}}');
          {% endif %}
      {% endfor %}
  </script>
   <script>
      var dt = new Date();
      document.getElementById("datetime").innerHTML = '<i class="bi bi-clock-history"></i> ' + dt.toLocaleString();
      
      setInterval(function() {
          dt = new Date();
          document.getElementById("datetime").innerHTML = '<i class="bi bi-clock-history"></i> ' + dt.toLocaleString();
      }, 1000);
   </script>
   <script src="https://kit.fontawesome.com/a076d05399.js"></script>
   <script>
      $(window).on('unload', function(){
          navigator.sendBeacon("{% url 'usuario:sair' %}", {});
      });
  </script>
</html>

usuario/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br" style="height: 100%;">
   <head>
      <title>Login - DefPdv</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      <link rel="stylesheet" href="{% static 'pdv/css/style.css' %}">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
      <!-- Default theme -->
      <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>
   </head>
   <body  style="height: 100%;   background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)),   url({% static 'pdv/img/login_auto_x2.jpg' %}) no-repeat;  background-size: cover;">
      <div class="container h-100">
         <div class="row justify-content-center align-items-center h-100">
             <div class="card col-8 bg-light shadow-lg"> <!-- Adicionei a classe shadow-lg aqui -->
                 <div class="row no-gutters">
                     <div class="col-6 d-flex justify-content-center align-items-center">
                         <img src="{% static 'pdv/img/DefPdv.png' %}" alt="Logo" style="width: 80%;">
                     </div>
                     <div class="col-6">
                         <div class="card-body d-flex flex-column">
                             <h1 class="text-center">Bem-vindo!</h1>
                             <form method="POST" action="{% url 'usuario:validar_login' %}" class="mt-auto">
                                 {% csrf_token %}
                                 <div class="form-group">
                                     <label for="nome">Nome:</label>
                                     <input type="text" class="form-control" name="nome" id="nome" placeholder="Digite o seu nome de usuário" required>
                                 </div>
                                 <div class="form-group">
                                     <label for="senha">Senha:</label>
                                     <input type="password" class="form-control" id="senha" name="cpf" placeholder="Digite a sua senha" required>
                                 </div>
                                 <div class="form-group text-center">
                                     <button type="submit" class="btn btn-primary">Entrar</button>
                                 </div>
                             </form>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
     
   </body>
   <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
   <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
   <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
   <script>
      alertify.set('notifier','position', 'top-right');
      {% for message in messages %}
          {% if message.tags == 'success' %}
              alertify.success('{{message}}');
          {% elif message.tags == 'error' %}
              alertify.error('{{message}}');
          {% else %}
              alertify.notify('{{message}}');
          {% endif %}
      {% endfor %}
  </script>
</html>